name: Publish package to the internal Maven Repository
on:
  schedule:
  #- cron:  "0 0 * * 0" #Every Sunday at midnight
  workflow_dispatch:
jobs:
  publish:
    name: "Perform Maven deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Publish package
        #run: mvn -B deploy
        run: mvn -B deploy -s settings.xml -Drepo.id=internal.repo -Drepo.username=$GITHUB_ACTOR -Drepo.token=$GITHUB_TOKEN -Dinternal.repo.url=$INTERNAL_REPO_URL -DaltDeploymentRepository=internal.repo::default::$INTERNAL_REPO_URL
        env:
          INTERNAL_REPO_URL: "https://maven.pkg.github.com/rajivmb/p13i-mvn-repo"
          #GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
