name: Purge and Publish Package to Internal Maven Repository
on:
  workflow_dispatch:
  schedule:
  - cron:  "0 0 * * *" #Every Sunday at midnight
env:
  PACKAGE_NAME: com.p13i.mit.aws.example.p13i-java-parent-example
  PACKAGE_VERSION: 1.0.0-SNAPSHOT
jobs:
  deploy:
    name: "Perform Purge and Publish"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Delete package version
        uses: ./.github/actions/delete-package-version
        with:
          name: com.p13i.mit.aws.example.p13i-java-parent-example
          version: 1.0.0-SNAPSHOT
          owner: ${{ github.repository_owner }}
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Perform Maven Deploy
        uses: ./.github/actions/perform-maven-deploy
        with:
          owner: ${{ github.repository_owner }}
          token: ${{ secrets.WORKFLOW_TOKEN }}
          internalRepoURL: "https://maven.pkg.github.com/rajivmb/p13i-mvn-repo"
