name: Purge and Publish Package to Internal Maven Repository
on:
  workflow_dispatch:
  schedule:
  - cron:  "0 0 * * 0" #Every Sunday at midnight
env:
  PACKAGE_NAME: com.p13i.mit.aws.example.p13i-java-parent-example
  PACKAGE_VERSION: 1.0.0-SNAPSHOT
jobs:
  deploy:
    name: "Perform Purge and Publish"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Delete package version
        uses: ./.github/actions/delete-package-version
        with:
          name: com.p13i.mit.aws.example.p13i-java-parent-example
          version: 1.0.0-SNAPSHOT
          owner: ${{ github.repository_owner }}
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven artifacts
        uses: actions/cache@v2
        env:
          cache-name: m2-cache
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Publish package
        run: mvn deploy -s settings.xml -Drepo.id=internal.repo -Drepo.username=${{ github.repository_owner }} -Drepo.token=$WORKFLOW_TOKEN -Dinternal.repo.url=$INTERNAL_REPO_URL -DaltDeploymentRepository=internal.repo::default::$INTERNAL_REPO_URL
        env:
          INTERNAL_REPO_URL: "https://maven.pkg.github.com/rajivmb/p13i-mvn-repo"
          WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
